libvirt: Autospec creation for update from version 9.6.0 to version 9.7.0
Andrea Bolognani (25):
      tests: Use DO_TEST_CAPS_*_ABI_UPDATE() for ppc64
      tests: Switch to firmware autoselection for hvf
      tests: Use virt-4.0 machine type for aarch64
      tests: Consistently use /path/to/guest_VARS.fd
      tests: Turn abi-update.xml into a symlink
      tests: Rename firmware-auto-efi-nvram-path
      qemu: Fix return value for qemuFirmwareFillDomainLegacy()
      qemu: Fix lookup against stateless/combined pflash
      tests: Add some more DO_TEST*ABI_UPDATE* macros
      tests: Add more tests for firmware selection
      tests: Update firmware descriptor files
      tests: Drop tags from BIOS firmware descriptor
      tests: Include microvm in firmwaretest
      qemu: Don't overwrite NVRAM template for legacy firmware
      qemu: Generate NVRAM path in more cases
      qemu: Filter firmware based on loader.readonly
      qemu: Match NVRAM template extension for new domains
      conf: Don't default to raw format for loader/NVRAM
      tests: Rename firmware-auto-efi-format-loader-qcow2-nvram-path
      tests: Reintroduce firmware-auto-efi-format-mismatch
      NEWS: Mention fixes to firmware selection
      ci: Fix precedence between arguments passed to meson
      ci: Fix quoting and option name
      rpm: Fix typo in daemon name
      rpm: Recommend libvirt-daemon for with_modular_daemons distros

Daniel P. Berrangé (3):
      src: fix max file limits in systemd services
      tools: fix handling of CPU family/model/stepping in SEV validation
      tools: fix VMSA construction with explicit CPU family/model/stepping

Erik Skultety (14):
      ci: integration: Drop the Fedora 35 check
      docs: index: Add a quick link to Submitting patches
      gitlab-ci.yml: Replace all explicit calls to ninja with meson commands
      gitlab-ci.yml: Use $HOME for rpmbuild's topdir instead of PWD
      ci: build.sh: Drop the commentary about CI_BUILD_SCRIPT
      ci: build.sh: Use 'meson setup' explicitly
      ci: build.sh: Always assume -Dsystem=true
      ci: build.sh: Drop the CI prefix from the CI_{MESON,NINJA}_ARGS vars
      ci: build.sh: Join MESON_ARGS and MESON_OPTS
      ci: Add Debian-12 target
      ci: Move Debian-11 workloads to Debian-12
      ci: Introduce a new 'lcitool' data directory
      ci: Udate FreeBSD-13 image with lcitool manifest
      ci: lcitool: Maintain project package deps lists here

Göran Uddeborg (2):
      Translated using Weblate (Swedish)
      Translated using Weblate (Swedish)

Jim Fehlig (1):
      libvirt-guests: Remove unused variable 'libvirtd'

Jiri Denemark (3):
      Post-release version bump to 9.7.0
      po: Refresh potfile for v9.7.0
      Release of libvirt-9.7.0

Jonathon Jongsma (1):
      run: add ability to set selinux context

Ján Tomko (1):
      qemu: remove pointless qemuDomainLogContextMode

K Shiva Kiran (8):
      Add <title> and <description> for Network Objects
      Adding Public Get and Set APIs for Network Metadata
      Implementing Remote Protocol for Network Metadata
      virsh exposure of Network Metadata APIs
      Add virNetworkObj Get and Set Methods for Metadata
      Add Test driver and testcase for Network Metadata change APIs
      Added bridge driver implementation
      virsh: Fix net-desc --config output

Kristina Hanicova (3):
      conf: add virDomainDiskBlockIoCheckABIStability()
      conf: add support for discard_granularity
      qemu: add support for discard_granularity

Laine Stump (11):
      qemu: don't add --mac-addr option to passt commandline
      util: use "stubDriverType" instead of just "stubDriver"
      util: add stub driver name to virPCIDevice object
      util: rename virPCIDeviceGetDriverPathAndName
      util: permit existing binding to VFIO variant driver
      util: probe stub driver from within function that binds to stub driver
      util: honor stubDriverName when probing/binding stub driver for a device
      node_device: support binding other drivers with virNodeDeviceDetachFlags()
      qemu: turn two multiline log messages into single line
      docs: update description of virsh nodedev-detach --driver option
      NEWS: document support for VFIO variant drivers

Laura Hild (1):
      Don't set cur=inf RLIM_NOFILE on macOS

Michal Prívozník (40):
      domain_event: Drop virDomainEventMemoryDeviceSizeChangePtr
      Revert "qemu_passt: Actually use @logfd"
      Revert "qemu_passt: Precreate passt logfile"
      tools: Fix vshControl declaration and initialization
      virt-aa-helper: Use struct zero initializer instead of memset
      Decrease scope of some variables
      qemu: Don't reuse variable in processSerialChangedEvent()
      remote_driver: Drop explicit memset(&sargs) in remoteAuthSASL()
      virfirewalld: Drop useless memset() in virFirewallDApplyRule()
      virnetlink: Drop unused variable from virNetlinkCommand()
      virnetclient: Update comment about memset()
      virnetdaemon.c: Use struct zero initializer instead of memset
      lib: use struct zero initializer instead of memset
      lib: Finish using struct zero initializer manually
      lib: Prefer sizeof(variable) instead of sizeof(type) in memset
      lxc_container: Increase stack size for lxcContainerChild()
      qemu: Generate shorter channel target paths
      qemu: Move channelTargetDir into stateDir
      qemu_domain: Drop unused variables from qemuDomainChrDefDropDefaultPath()
      virt-aa-helper: Rework setting virDomainMemoryDef labels
      virt-aa-helper: Set label on VIRTIO_PMEM device too
      qemu_hotplug: validate address on memory device change
      qemu_hotplug: Don't validate inaccessible fields in qemuDomainChangeMemoryLiveValidateChange()
      conf: Compare memory device address in virDomainMemoryFindByDefInternal()
      qemu_driver: validate mem->model on MEMORY_DEVICE_SIZE_CHANGE event
      src: Move _virDomainMemoryDef source nodes into an union
      src: Move _virDomainMemoryDef target nodes into an union
      src: Rename some members of _virDomainMemoryDef struct
      virfile: Introduce virCloseRange()
      virfile: Introduce virCloseFrom()
      vircommand: Unify mass FD closing
      vircommand: Introduce virCommandMassCloseRange()
      src: Detect close_range syscall during virGlobalInit()
      nodedevmdevctltest: Rename mdevctl-list-empty test case
      nodeDeviceParseMdevctlJSON: Accept empty string
      nodedevmdevctltest: Introduce a test case for empty mdevctl output
      node_device_driver: Deduplicate mediated devices listing
      virMdevctlList: Don't check for !output
      virjsontest: Introduce a test case for an empty array
      virsh-network: Drop unused variables in cmdNetworkMetadata()

Pavel Hrdina (28):
      libvirt_private: list virDomainMomentDefPostParse
      snapshot_conf: export virDomainSnapshotDiskDefClear
      snapshot_conf: use alternate domain definition in virDomainSnapshotDefAssignExternalNames
      snapshot_conf: introduce <revertDisks> metadata element
      virDomainSnapshotAlignDisks: Allow overriding user-configured snapshot default
      qemu_snapshot: introduce qemuSnapshotDomainDefUpdateDisk
      qemu_snapshot: use virDomainDiskByName while updating domain def
      qemu_snapshot: introduce qemuSnapshotCreateQcow2Files
      qemuSnapshotCreateQcow2Files: use domain definition directly
      qemu_snapshot: move external disk prepare to single function
      qemu_snapshot: use VIR_ASYNC_JOB_SNAPSHOT when reverting snapshot
      qemu_snapshot: introduce external snapshot revert support
      qemu_snapshot: rename qemuSnapshotDeleteExternalPrepare
      qemu_snapshot: extract external snapshot delete prepare to function
      qemu_snapshot: add merge to external snapshot delete prepare data
      qemu_snapshot: prepare data for non-active leaf external snapshot deletion
      qemu_snapshot: add support to delete external snapshot without block commit
      qemu_snapshot: delete: properly update parent snapshot with revert data
      qemu_snapshot: remove revertdisks when creating new snapshot
      virdomainmomentobjlist: introduce virDomainMomentIsAncestor
      qemuDomainGetImageIds: pass domain definition directly
      qemu_snapshot: update backing store after deleting external snapshot
      qemu_snapshot: check only once if snapshot is external
      qemu_snapshot: add checks for external snapshot deletion
      qemu_snapshot: allow snapshot revert for external snapshots
      capabilities: reword disksnapshot feature to mention creating snapshots
      capabilities: report full external snapshot support
      Revert "capabilities: report full external snapshot support"

Peter Krempa (43):
      virLXCControllerSetupUsernsMap: Modify debug logging for clean startup errors
      virLXCProcessReadLogOutputData: Refill buffer after filtering out noise
      virLXCProcessReportStartupLogError: Strip trailing newline from error
      daemon: Treat logging of VIR_ERR_MULTIPLE_INTERFACES same as VIR_ERR_NO_INTERFACE
      virStorageBackendLogicalCheckPool: Properly mark empty logical pools as active
      qemuMigrationSrcBeginPhase: Properly report error when non-shared storage migration is requested over tunnel
      qemuMigrationSrcBeginPhase: Require storage migration when 'migrate_disks' parameter is specified
      virsh: doMigrate: Rework virsh option to migration flag conversion
      virsh: doMigrate: Require --copy-storage-(all|inc) with --migrate-disks
      test: qemu: Update qemu-8.1 test data on x86_64
      qemuxml2argvtest: Drop 'master-key' test case
      qemuxml2(argv|xml)test: Modernize 'net-many-models' case
      qemuxml2argvdata: Replace 'qemu-system-i386' by 'qemu-system-x86_64' in most test files
      qemuxml2(argv|xml)test: Convert certain tests to DO_TEST_CAPS_LATEST
      qemuxml2argvdata: Convert 'cpu' test cases to use 'x86_64'
      testutilsqemu: Drop fake data for VIR_ARCH_I686
      qemuxml2xmltest: Modernize all 'DO_TEST_NOCAPS' tests
      qemuxml2xmloutdata: Workaround wrong detection of 'disk-cdrom-empty-network-invalid' in virschematest
      virschematest: Improve detection of 'invalid' XMLs
      qemuxml2xmltest: Use real caps for 'vxhs' disk tests
      qemuxml2xmltest: Convert rest of 'DO_TEST_NOCAPS' cases to 'DO_TEST_CAPS_LATEST'
      qemuxml2(argv|xml)test: Modernize 'graphics-dbus*' tests
      qemuxml2(argv|xml)test: Sanitize testing of default video type on x86_64
      qemuValidateDomainVCpuTopology: Always validate vcpu count against topology
      qemuxml2(argv|xml)test: Modernize 'fd-memory*' test cases
      qemuxml2(argv|xml)test: Modernize 'shmem' test cases
      qemu: Retire 'ivshmem' device
      qemu: capabilities: Retire unused QEMU_CAPS_DEVICE_IVSHMEM
      qemuxml2argvtest: Moderinze 'video-*' cases
      qemuxml2xmltest: Modernize all 'video-*' cases
      qemuxml2argvtest: Modernize 'net-*'
      qemuxml2xmltest: Modernize all 'net-' tests
      qemuxml2xmltest: Modernize all remaining fake capability tests
      qemuValidateDomainVCpuTopology: Remove misconfiguration warning
      tests: chxml2xmlin: Fix path format for fake paths
      virschematest: Validate files in 'chxml2xmlin' and 'chxml2xmlout' directories
      qemuxml2xmltest: Rework file name generation in 'testInfoSetPaths'
      qemuxml2xmltest: Use DO_TEST_CAPS_ARCH_LATEST_FULL for arm GIC tests
      qemuxml2argvtest: Pass expected state via struct testQemuInfo's 'flags' member
      qemuxml2xmltest: Modernize rest of 'seclabel-*' tests
      qemuxml2xmltest: Merge DO_TEST macro into DO_TEST_CAPS_INTERNAL
      qemucapabilitiesdata: Final update of capability test data for qemu-8.1.0 release
      docs: Improve documentation of <disk type='dir'>

Weblate (1):
      Update translation files

Yuri Chornoivan (1):
      Translated using Weblate (Ukrainian)

Анастасия Белова (1):
      conf: fix error message

김인수 (2):
      Translated using Weblate (Korean)
      Translated using Weblate (Korean)