libvirt: Autospec creation for update from version 9.7.0 to version 9.8.0
Anastasia Belova (1):
      qemu: Add VIR_FREE in ADD_BITMAP

Andrea Bolognani (15):
      rpm: Install client-qemu with main package
      qemu: Improve error message for failed firmware autoselection
      systemd: Add missing Also for admin socket
      systemd: Add missing WantedBy for virtlogd/virtlockd
      systemd: Add missing Service for virtlogd/virtlockd
      systemd: Set Type=notify for virtlogd/virtlockd
      systemd: Set @name@ for virtlogd/virtlockd
      systemd: Rename socket_in_def -> socket_in_default
      systemd: Rename @mode@ -> @sockmode@
      systemd: Only set @sockmode@ once
      systemd: Drop unnecessary uses of @sockets@
      systemd: Make @sockprefix@ optional
      systemd: Drop unnecessary uses of @sockprefix@
      docs: Go bindings release at the same time as the C library
      rpm: Drop with_vz define

Boris Fiuczynski (1):
      qemuxml2argvtest: Fix tests failing on none x86 host CPUs

Dmitry Frolov (2):
      fix virCgroupGetMemoryStat arguments order
      interface: fix udev_device_get_sysattr_value return value check

Erik Skultety (49):
      ci: lcitool: Add libvirt-tck+runtime deps list
      ci: build.sh: Add variables from .gitlab-ci.yml
      ci: build.sh: Add GIT_ROOT env helper variable
      ci: build.sh: Don't mention that MESON_ARGS are available via CLI
      ci: build.sh: Add a wrapper function executing 'shell' commands
      ci: build.sh: Add a wrapper function over meson's setup
      ci: build.sh: Add a wrapper function over the 'build' job
      ci: build.sh: Add a helper function to create the dist tarball
      ci: build.sh: Add a wrapper function over the 'test' job
      ci: build.sh: Add a wrapper function over the 'codestyle' job
      ci: build.sh: Add a wrapper function over the 'potfile' job
      ci: build.sh: Add a wrapper function over the 'rpmbuild' job
      ci: build.sh: Add a wrapper function over the 'website' job
      ci: build.sh: Drop changing working directory to CI_CONT_DIR
      ci: build.sh: Drop direct invocation of meson/ninja commands
      ci: build.sh: Drop MESON_ARGS definition from global level
      ci: Rename build.sh -> jobs.sh
      .gitlab-ci.yml: Add 'after_script' stage to prep for artifact collection
      .gitlab-ci.yml: Convert the native build job to the build.sh usage
      .gitlab-ci.yml: Convert the cross build job to the build.sh usage
      .gitlab-ci.yml: Convert the website build job to the build.sh usage
      .gitlab-ci.yml: Convert the codestyle job to the build.sh usage
      .gitlab-ci.yml: Convert the potfile job to the build.sh usage
      ci: helper: Drop _lcitool_get_targets method
      ci: helper: Don't make ':' literal a static part of the image tag
      ci: helper: Add --lcitool-path CLI option
      ci: helper: Add a required_deps higher order helper/decorator
      ci: helper: Add Python code hangling git clones
      ci: helper: Add a helper to create a local repo clone Pythonic way
      ci: helper: Rework _lcitool_run method logic
      ci: helper: Add an action to run the container workload via lcitool
      ci: helper: Add a job argparse subparser
      ci: helper: Drop original actions
      ci: helper: Drop the --meson-args/--ninja-args CLI options
      ci: helper: Drop the _make_run method
      ci: Drop the now unused Makefile
      ci: jobs.sh: Add back '--no-suite syntax-check --print-errorlogs'
      syntax-check: Drop the shell's 'check for minus' rule
      ci: integration: Extract the integration CI main recipe to jobs.sh
      ci: integration: Adjust the check for CentOS Stream version
      ci: integration: Drop the 'install-deps' hidden job and reference
      ci: jobs.sh: Drop comment about the need for Avocado 98.0
      ci: jobs.sh: integration: Use --quiet with virsh
      ci: jobs.sh: run_integration: Add/Rewrite/Reformat commentaries
      ci: jobs.sh: run_integration: Make POSIX-compliant
      ci: jobs.sh: Introduce a quiet version of run_cmd
      ci: jobs.sh: integration: Execute commands via 'run_cmd[_quiet]' helpers
      ci: jobs.sh: run_integration: Print DAEMONS variable for debugging
      ci: jobs.sh: Define and create SCRATCH_DIR for local executions

Jim Fehlig (2):
      libxl: Fix Domain-0 ballooning logic
      libxl: Fix connection to modular network daemon

Jiri Denemark (3):
      Post-release version bump to 9.8.0
      po: Refresh potfile for v9.8.0
      Release of libvirt-9.8.0

Jonathon Jongsma (44):
      conf: add ability to configure a vdpa block disk device
      qemu: add virtio-blk-vhost-vdpa capability
      qemu: make vdpa connect function more generic
      qemu: consider vdpa block devices for memlock limits
      qemu: Implement support for vDPA block devices
      schema: allow 'ssh' as a protocol for network disks
      qemu: Add functions for determining nbdkit availability
      qemu: expand nbdkit capabilities
      util: Allow virFileCache data to be any GObject
      qemu: implement basic virFileCache for nbdkit caps
      qemu: implement persistent file cache for nbdkit caps
      qemu: use file cache for nbdkit caps
      qemu: Add qemuNbdkitProcess
      qemu: query nbdkit module dir from binary
      qemu: add functions to start and stop nbdkit
      Generalize qemuDomainLogContextNew()
      qemu: Extract qemuDomainLogContext into a new file
      qemu: move qemuProcessReadLog() to qemuLogContext
      qemu: log error output from nbdkit
      tests: add ability to test various nbdkit capabilities
      qemu: split qemuDomainSecretStorageSourcePrepare
      qemu: include nbdkit state in private xml
      util: secure erase virCommand send buffers
      qemu: pass sensitive data to nbdkit via pipe
      qemu: use nbdkit to serve network disks if available
      util: make virCommandSetSendBuffer testable
      tests: add tests for nbdkit invocation
      qemu: add test for authenticating a https network disk
      qemu: Add Taint for nbdkit restart failure
      qemu: Monitor nbdkit process for exit
      qemu: try to connect to nbdkit early to detect errors
      schema: add password configuration for ssh disk
      qemu: implement password auth for ssh disks with nbdkit
      schema: add configuration for host verification of ssh disks
      qemu: implement knownHosts for ssh disks with nbdkit
      schema: add keyfile configuration for ssh disks
      qemu: implement keyfile auth for ssh disks with nbdkit
      schema: add ssh-agent configuration for ssh disks
      qemu: implement ssh-agent auth for ssh disks with nbdkit
      rpm: update spec file for for nbdkit support
      ci: add libnbd to build
      util: Fix error return for virProcessKillPainfullyDelay()
      news: document support for vdpa block devices
      news: document nbdkit support for network disks

Ján Tomko (3):
      qemu: fix indentation in qemuValidateDomainDeviceDefFS
      qemu: extend filesystem XML validation
      docs: formatdomain: clarify support of some filesystem options

K Shiva Kiran (8):
      NEWS: Announcing Network Metadata APIs
      Define Network Metadata change event
      conf: Add methods to create Metadata change events
      remote: Implement client side of network netadata change event
      test_driver: Emit network metadata change event
      network: Emit Emit network metadata change event
      examples: Report network metadata change event
      NEWS: Documnet network metadata change event

Martin Kletzander (4):
      tests: Remove unused symlink
      conf, schema: Switch iothread/poll values to unsignedLong
      docs, passt: Clarify some niche passt usage
      conf: Generate MAC address instead of keeping all zeroes

Michal Prívozník (72):
      bhyve: Move error messages onto a single line
      ch: Move error messages onto a single line
      conf: Move error messages onto a single line
      cpu: Move error messages onto a single line
      esx: Move error messages onto a single line
      hypervisor: Move error messages onto a single line
      libxl: Move error messages onto a single line
      locking: Move error messages onto a single line
      lxc: Move error messages onto a single line
      network: Move error messages onto a single line
      node_device: Move error messages onto a single line
      nwfilter: Move error messages onto a single line
      openvz: Move error messages onto a single line
      qemu: Move error messages onto a single line
      remote: Move error messages onto a single line
      rpc: Move error messages onto a single line
      security: Move error messages onto a single line
      storage: Move error messages onto a single line
      storage_file: Move error messages onto a single line
      test: Move error messages onto a single line
      util: Move error messages onto a single line
      vbox: Move error messages onto a single line
      vmware: Move error messages onto a single line
      vmx: Move error messages onto a single line
      vz: Move error messages onto a single line
      src: Move error messages onto a single line
      tools: Move error messages onto a single line
      docs: Document that libxl hooks are also given full domain XML
      docs: Document bhyve hook scripts
      bhyve: Feed hook scripts with domain XML
      tools: Reformat --help output of virsh and virt-admin
      syntax-check: Introduce a rule for one line error messages
      ch: Use uint for @maxvcpus in virCHDomainRefreshThreadInfo()
      ch: Use int for @niothreads in virCHMonitorGetIOThreads()
      ch: Use proper format directive for @i in virCHProcessSetupIOThreads()
      storage_util: Drop getDeviceType()
      virsh-snapshot: Avoid passing NULL to qsort() in virshSnapshotListCollect()
      virnetdevopenvswitch: Propagate OVS error messages
      lxc_container: Check retval of capng_get_caps_process()
      virutil: Check retval of capng_apply()
      lxc_controller: Access correct union member in virLXCControllerSetupHostdevCaps()
      src: Access hostdev->source.subsys iff VIR_DOMAIN_HOSTDEV_MODE_SUBSYS
      qemu_domain_address: Drop needless typecast in qemuDomainDeviceCalculatePCIConnectFlags()
      qemu: Drop needless typecast to virDomainFSDriverType
      src: Drop needless typecast to virDomainDeviceType
      qemu_domain_address: Drop needless typecast to virDomainDiskModel
      src: Drop needless typecast to virDomainDiskBus
      virDomainHostdevSubsysSCSI: Convert 'protocol' field to proper enum type
      virDomainHostdevSubsysSCSIVHost: Convert 'protocol' field to proper enum type
      virDomainHostdevDef: Convert 'mode' field to proper enum type
      virDomainHostdevCaps: Convert 'type' field to proper enum type
      virDomainHostdevSubsys: Convert 'type' field to proper enum type
      virDomainControllerDef: Convert 'type' field to proper enum type
      virDomainRNGDef: Convert 'model' field to proper enum type
      virDomainRNGDef: Convert 'backend' field to proper enum type
      virDomainWatchdogDef: Convert 'model' field to proper enum type
      virDomainWatchdogDef: Convert 'action' field to proper enum type
      virDomainDeviceInfo: Convert 'type' field to proper enum type
      virStorageNetHostDef: Convert 'transport' field to proper enum type
      virDomainDiskSourceNVMeParse: Use virXMLPropULongLong()
      bhyveBuildControllerArgStr: Fill in missing cases to switch() statement
      src: Avoid needless checks before calling g_strdup()
      virnetdevvportprofile: Turn virNetDevVPortProfileLinkOp enum into a proper typedef
      virNetDevVPortProfileOp8021Qbh: Use proper type in virReportEnumRangeError()
      virDomainVideoDefValidate: Use proper type in virReportEnumRangeError()
      virerror: Make virReportEnumRangeError() check for type mismatch
      test_driver: Implement virConnectGetDomainCapabilities()
      domain_validate: Validate VIRTIO_PMEM address alignment
      virDomainMemoryDefValidate: Fix VIRTIO_MEM alignment check
      virDomainMemoryDefValidate: Check for overlapping memory devices
      NEWS: Fix placement of network metadata entry
      NEWS: Document my contributions for upcoming release

Pavel Hrdina (1):
      qemu_nbdkit: fix possible null dereference

Peter Krempa (80):
      qemu: Rename qemuDomainSupportsNewVcpuHotplug to qemuDomainSupportsVcpuHotplug
      qemu: capabilities: Export functions necessary for probing machine types
      qemu: process: Probe machine type data on reconnect to qemu
      qemuxml2argvtest: Modernize 'cpu-hotplug-startup' case
      tests: qemuhotplugtest: Fix arch-specific parts of 'ppc64' test XMLs
      qemuhotplugtest: Remove 'modern' field for cpu hotplug tests
      qemuDomainSupportsVcpuHotplug: Base return value on virQEMUCapsGetMachineHotplugCpus
      qemu: capabilities: Retire QEMU_CAPS_QUERY_HOTPLUGGABLE_CPUS
      qemu: capabilities: Remove unused 'virQEMUCapsFilterByMachineType'
      virNetworkDNSHostDefParseXML: Refactor parsing
      virsh: domain: Refactor XML handling for disk changes
      virDomainFeaturesCapabilitiesDefParse: Use virXMLNodeGetSubelementList
      virDomainFeaturesKVMDefParse: Use virXMLNodeGetSubelementList
      virDomainFeaturesXENDefParse: Use virXMLNodeGetSubelementList
      bhyve: Don't stack-allocate huge error buffers
      virHostValidateBhyve: Declare one variable per line
      virHostValidateBhyve: Heap allocate massive 'struct kld_file_stat'
      nss: aiforaf: Format one argument/variable per line
      nss: aiforaf: Remove unused 'ret' variable
      nss: aiforaf: Drop unused buffer 'port'
      nss: aiforaf: Decrease stack size by scoping off large buffers
      build: Decrease maximum stack frame size to 2048
      docs: compiling: Add a note about use of CFLAGS for optimization
      build: Work around clang's stack size calculation without optimization
      build: Fix assignment into 'stack_frame_size' when sanitizer is enabled
      build: Fix logic bug determining whether running with optimization
      securityselinuxlabeltest: Convert to testQemuInsertRealCaps
      qemu: Always assume support for QEMU_CAPS_PIIX_DISABLE_S* and QEMU_CAPS_ICH9_DISABLE_S*
      qemu: capabilities: Retire QEMU_CAPS_ICH9_DISABLE_S* and QEMU_CAPS_ICH9_DISABLE_S* capabilities
      qemu: capabilities: Preserve location of the default machine type when stripping aliases for tests
      qemuxml2argvtest: Clean up host CPU if overriden
      qemuxml2argvtest: testAddCPUModels: Remove non-x86_64 fake cpu models
      qemuxml2argvtest: Drop 'monitor-json' case
      qemu: Always assume support for QEMU_CAPS_CPU_CACHE
      qemu: capabilities: Retire QEMU_CAPS_CPU_CACHE
      qemu: Always assume support for QEMU_CAPS_DEVICE_VFIO_PCI
      qemu_capabilities: Retire QEMU_CAPS_DEVICE_VFIO_PCI
      qemuxml2argvtest: Add missing versioned test cases for 'cpu-host-model'
      qemuxml2argvtest: Remove old chardev tests
      qemuxml2argvtest: Simplify invocation of GIC tests
      qemuxml2argvtest: Remove duplicated test invocations
      qemuxml2argvtest: Remove fake-caps invocations of tests which also real caps version
      qemuxml2argvtest: Use proper version in negative 'virtio-options-memballoon-freepage-reporting' case
      qemuxml2argvtest: Use real caps for 'cpu-host-model-fallback' test case
      qemuxml2argvtest: Use real caps for 'cpu-host-model-nofallback' test case
      qemuxml2argvtest: Remove FLAG_SKIP_LEGACY_CPUS
      qemuxml2argvtest: Enable JSON syntax for -device, -object, and -netdev for all fake-caps tests
      virQEMUCapsAddCPUDefinitions: Fill in cpu type in data and node it's used only in tests
      qemuxml2argvtest: Modernize negative testing for hugepages
      qemuxml2argvtest: Modernize 'numatune' tests
      testutilsqemu: Always populate default ram id, default cpu, ACPI support for fake machines
      qemuxml2argvtest: Enable 'seccomp' sandbox in all fake caps tests
      qemuxml2argvtest: Consolidate tests for usb controllers
      qemuxml2argvtest: Add tests for auto-added USB controllers
      qemuxml2argvtest: Improve default usb controller testing
      qemuxml2argvtest: Consolidate testing of 'xhci' controllers
      qemuxml2argvtest: Assume QEMU_CAPS_PIIX3_USB_UHCI for all fake-caps tests
      qemuxml2argvtest: Assume QEMU_CAPS_DEVICE_PCIE_ROOT_PORT for fake-caps tests
      qemuxml2argvtest: Assume QEMU_CAPS_CPU_MIGRATABLE and QEMU_CAPS_SMP_DIES for fake-caps tests
      qemuxml2argvtest: Assume QEMU_CAPS_USB_HOST_HOSTDEVICE and QEMU_CAPS_DEVICE_QEMU_XHCI for fake-caps tests
      qemuxml2argvtest: Assume QEMU_CAPS_QXL_VRAM64, QEMU_CAPS_(QXL|VGA)_VGAMEM for fake-caps tests
      qemuxml2argvtest: Properly modernize 'clock-hpet-off' test case
      qemuxml2argvtest: Modernize migration/restore tests
      qemuxml2argvtest: Consolidate and modernize CPU topology testing
      qemuxml2argvtest: Modernize test cases using 'host-model' CPU
      qemuxml2argvtest: Modernize 'cpu-Haswell' test cases
      qemuxml2argvtest: Modernize 'cpu-minimum' cases
      qemuxml2argvtest: Modernize 'cpu-strict' case
      qemuxml2argvtest: Modernize 'cpu-(no)fallback' test
      qemuxml2argvtest: Modernize 'cpu-exact' cases
      qemuxml2argvtest: Modernize rest of the test cases
      testutilsqemu: Drop fake machine capability data for 'x86_64'
      qemustatusxml2xmltest: Remove capabilities infrastructure
      testutilsqemu: Drop infrastructure for fake-caps testing
      testutilsqemu: Unexport 'testQemuCapsInit'
      qemu: capabilities: Unexport 'virQEMUCapsAddMachine'
      qemuxml2argvtest: Remove cpu model faking for fake-caps tests
      qemu: capabilities: Remove 'virQEMUCapsAddCPUDefinitions'
      manpage: virsh: Note that 'virsh undefine --remove-all-storage' doesn't remove backing images
      virStorageSourceClear: Clear 'vdpadev' field

Praveen K Paladugu (1):
      ch: Fix cloud-hypervisor version processing

Tim Wiederhake (2):
      cpu_map: Ignore all vmx-* features in sync_qemu_features_i386.py
      cpu_map: Add cpu model EPYC Genoa

Weblate (1):
      Update translation files

Yuri Chornoivan (1):
      Translated using Weblate (Ukrainian)

김인수 (4):
      Translated using Weblate (Korean)
      Translated using Weblate (Korean)
      Translated using Weblate (Korean)
      Translated using Weblate (Korean)