libvirt: Autospec creation for update from version 11.0.0 to version 11.1.0
Adam Julis (3):
      conf: check size of secret file for secret object
      Support IDE/SATA disk 'product' parameter
      glibcompat: Sync g_string_replace()

Andi Chandler (2):
      Translated using Weblate (English (United Kingdom))
      Translated using Weblate (English (United Kingdom))

Andrea Bolognani (4):
      meson: Unify handling of directories used for loadable modules
      rpm: Add missing Requires
      rpm: Unify handling of directories used for loadable modules
      utils: Canonicalize paths before comparing them

Anirudh Rayabharam (1):
      ch: implement domainInterfaceAddresses

Ankush Menat (1):
      docs: add missing cellNum parameter in function call

Anonymous (1):
      Translated using Weblate (Telugu)

Assaf Admi (1):
      docs: Document that 'vcpu.delay' statistic is in nanoseconds

Boris Fiuczynski (10):
      nodedev: refactor CCW device address format
      nodedev: refactor CCW device address
      nodedev: remove virNodeDeviceCapCCWDefFormat
      nodedev: refactor CCW state format for use in ccwgroup
      nodedev: refactor udevCCWGetState
      nodedev: add ccwgroup node device support
      nodedev: add ccwgroup capability support to ccw devices
      nodedev: add qeth layer2 and layer3 device types
      node_device_udev: add error reporting to udevProcessCCWGroup
      NEWS: Document ccwgroup based qeth device support

Bronek Kozicki (1):
      tools: Move libvirt-guests lock file out of subsys directory

Cole Robinson (1):
      spec: Only build ch driver on x86_64 and aarch64

Daniel Henrique Barboza (4):
      qemu: add capability for RISC-V AIA feature
      conf,qemu: implement RISC-V 'aia' virt domain feature
      qemu: add RISC-V 'aia' command line
      .mailmap: add my contact info

Daniel P. Berrangé (15):
      util: avoid overflow in hextable buffer
      remote: add sysusers file to create 'libvirt' group
      tools: add sysusers file to create 'virtlogin' group
      rpm: disable account creation for Fedora >= 42
      Translated using Weblate (Chinese (Traditional) (zh_TW))
      ci: refresh with 'lcitool manifest'
      bhyve: add 'driver' to bhyveProcessStart method
      bhyve: stop opening & passing connection to bhyveProcessStart
      util: add APIs for more systemd notifications
      remote: notify systemd when reloading config
      hypervisor: introduce helper for autostart
      src: convert drivers over to use new autostart helper
      hypervisor: add support for delay interval during autostart
      qemu: add 'auto_start_delay' configuration parameter
      build-aux: squelch trailing blank warnings from binary files

Fabian Leditzky (1):
      qemu: Check empty drives in block I/O throttle API

Fabricio Duarte (1):
      docs: fix 'virsh domstats --vcpu' measure units and descriptions

Guoyi Tu (1):
      nodedev: udev: Hook up virFileWaitForExist to address uevent race of pci device

Heinrich Schuchardt (1):
      virsysinfo: fix RISC-V detection

Jiang XueQian (1):
      nss: Skip empty files and avoid use of uninitialized value

Jim Fehlig via Devel (3):
      qemu: Move unlinking corrupt save image file to caller
      qemu: Decompose qemuSaveImageOpen
      qemu: Check for valid save image format when verifying image header

Jiri Denemark (29):
      Post-release version bump to 11.1.0
      qemu: Report error from both sides of migration
      qemu_migration: Refactor qemuMigrationSrcRestoreDomainState
      qemu_migration: Do not automatically resume domain after I/O error
      cpu_x86: Probe host CPU for all MSR features
      qemu: Fix hang when migration is canceled at the last moment
      Add a migration parameter for available bandwidth in switchover
      virsh migrate: Add --available-switchover-bandwidth option
      qemu: Add support for avail-switchover-bandwidth migration parameter
      qemu: Allow virDomainBlockJobSetSpeed during migration
      qemu: Avoid crash in qemuDomainCheckCPU with unknown host CPU
      docs: Clarify documentation of virsh hypervisor-cpu-compare
      docs: Clarify documentation of virsh hypervisor-cpu-baseline
      virsh: Do not format messages twice
      virsh: Make messages printed by vshError properly translatable
      virsh: Refactor vshError
      virsh: Introduce vshWarn
      virsh: Warn when hypervisor-cpu-* is used with host CPU
      virsh: Do not require \n in vshDebug messages
      virsh: Properly mark all error messages for translation
      virsh: Avoid using translated messages without format
      virsh: Drop extra newlines at the end of error messages
      virsh: Let prohibit_newline_at_end_of_diagnostic check pass
      build: Enable syntax checks for vshError and vshWarn
      po: Refresh potfile for v11.1.0
      run: Use correct SELinux context for modular daemons
      cpu: Do not call g_strv_contains on NULL list
      NEWS: Document crasher fix in qemuDomainCheckCPU
      Release of libvirt-11.1.0

Ján Tomko (4):
      meson: error out when ch driver is requested but unsupported
      libvirt.spec: do not build ch driver on mingw
      docs: index: fix VMware capitalization
      docs: formatdomain: fix typo in passt section

Laine Stump (16):
      conf: change virDomainHostdevInsert() to return void
      qemu: fix qemu validation to forbid guest-side IP address for type='vdpa'
      qemu: validate that model is virtio for vhostuser and vdpa interfaces in the same place
      qemu: automatically set model type='virtio' for interface type='vhostuser'
      qemu: do all vhostuser attribute validation in qemu driver
      conf/qemu: make <source> element *almost* optional for type=vhostuser
      qemu: use switch instead of if in qemuProcessPrepareDomainNetwork()
      qemu: make qemuPasstCreateSocketPath() public
      qemu: complete vhostuser + passt support
      qemu: fail validation if a domain def has vhostuser/passt but no shared mem
      docs: improve type='user' docs to higlight differences between SLIRP and passt
      docs: document using passt backend with <interface type='vhostuser'>
      news: include info about supporting vhostuser+passt combination
      util: fix compile warning in virsystemd.c during mingw builds
      tests: be consistent about following DO_TEST_*() with a ;
      schema: fix <interleave> errors when validating <domain> subelements

Martin Kletzander (2):
      docs: Reword virDomainGetEmulatorPinInfo description
      node_device: Do not lock the driver state needlessly

Michal Prívozník (21):
      qemuxmlconftest: Drop s390-default-cpu-...ccw-virtio-2.7 test cases
      tools: ssh-proxy: Check for domain status before parsing its CID
      ch: Include unistd.h in ch_events.c
      vbox: Use g_autofree in tryLoadOne()
      vbox: Report an error when VBox CAPI initialization fails
      vbox: Drop support for VirtualBox-6.1.x
      vbox: Drop code supporting old VBox version
      NEWS: Document VBOX-6.1 removal
      qemu: Do NOT autoadd NUMA node for s390
      qemu_command: Use qemuBuildVirtioDevProps() to build cmd line for virtio-mem and virtio-pmem
      qemuxmlconftest: Introduce memory-hotplug-virtio-mem-pci-s390x.xml
      qemu_caps: Introduce QEMU_CAPS_DEVICE_VIRTIO_MEM_CCW
      qemu: Validate virtio-mem-ccw
      qemu: Allow virtio-mem on CCW
      qemuxmlconftest: Introduce memory-hotplug-virtio-mem-ccw-s390x.xml
      NEWS: Document virtio-mem-ccw
      tests: qemuxmlconfdata: Update launch-security-sev-snp.xml
      virgdbus: Introduce virGDBusHasSessionBus()
      remote_daemon: Silence DBus errors
      apparmor: Allow SGX if configured
      NEWS: Document features/improvements/bug fixes I've participated in

Nicolas Gal (1):
      Translated using Weblate (Spanish)

Nicolás Gal (4):
      Translated using Weblate (Spanish)
      Translated using Weblate (Spanish)
      Translated using Weblate (Spanish)
      Translated using Weblate (Spanish)

Pavel Hrdina (3):
      qemu_snapshot: allow reverting to external disk only snapshot
      libvirt.spec.in: fix indentation
      qemu: fix qemuDomainSaveImageDefineXML

Peter Krempa (75):
      storage_file: Refuse qcow2 images with empty string as 'data_file'
      virstoragetest: Add case for qcow2 image with empty string as 'data_file'
      storage_file: de-modularize the local file backend
      NEWS: Mention de-modularization of the 'fs' storage file backend
      libvirt.spec: Move ownership of 'storage-file' backends directory to gluster
      storage_file_backend_fs: Compile out 'chown' backend on mingw
      build: Bump minimum glib2 version to 2.66.0
      qemuProcessHandleIOError: Refactor to extract 'priv' instead of 'driver'
      qemu: Handle quirks of 'device' field of BLOCK_IO_ERROR event in monitor code
      qemu: Rename 'diskAlias' to 'device' in qemu IO error event handling
      qemuProcessHandleIOError: Rename local variables
      qemuMonitorJSONHandleIOError: Do not munge 'reason' field of IO error event
      qemuProcessHandleIOError: Prefer lookup by node name
      qemuMonitorJSONHandleIOError: Propagate new 'qom-path' field
      virStorageSource: Add fields for storing last I/O error message
      qemuProcessHandleIOError: Populate I/O error reason to virStorageSource
      qemuProcessHandleIOError: Log IO errors in the VM log file
      libxlDomainGetMessages: Add existing flags to 'virCheckFlags'
      virDomainObjGetMessages: Refactor using GPtrArray
      virDomainGetMessages: Introduce VIR_DOMAIN_MESSAGE_IOERRORS
      include: libvirt-domain: Reword documentation for @reason of VIR_DOMAIN_EVENT_ID_IO_ERROR_REASON
      include: libvirt-domain: Add 'message' @reason of VIR_DOMAIN_EVENT_ID_IO_ERROR_REASON
      NEWS: Mention preserving I/O error messages for qemu VMs
      node_device_udev: Fix build failure in ccw device code
      qemuSnapshotForEachQcow2: Don't initialize 'nrollback'
      qemu: process: Export qemuPrepareNVRAM for use in snapshot code
      qemu: snapshot: Ensure that NVRAM image exists when taking inactive internal snapshot
      qemucapabilitiestest: Final update for qemu-9.2 release on x86_64
      qemucapabilitiestest: Add data for the qemu-10.0 dev cycle on x86_64
      qemu_hotplug.h: Reformat according to new coding style
      virDomainDefHasManagedPR: Consider also disk's 'mirror' chain
      qemu: hotplug: Export persistent reservations manager helper functions
      qemu: blockjob: Remove persistent reservations manager when dropping disk images
      qemu: Attach persistent reservations manager if block-copy target requires it
      qemuxmlconftest: Allow testing of the 'writable' flag for passed FDs for disks
      qemuxmlconftest: Add testing of FDs with 'writable' flag in 'disk-source-fd'
      qemu: domain: Initialize FD passthrough for a virStorageSource before using it
      qemu: snapshot: Limit scope of checkpoint-snapshot interlock
      qemu-replies-tool: Dump also query string for optional members
      qemucapabilitiestest: Update 'caps_10.0.0_x86_64' to 'v9.2.0-1636-gffaf7f0376'
      qemu: capabilies: Introduce QEMU_CAPS_BLOCKDEV_SET_ACTIVE
      qemu: monitor: Add monitor backend for 'blockdev-set-active'
      qemu: migration: Reactivate block nodes after migration if VM is left paused
      qemuDomainGetStatsBlockExportHeader: Remove return value
      qemuDomainGetStatsBlockExportFrontend: Remove return value
      qemuDomainGetStatsBlockExportBackendStorage: Remove return value
      qemuDomainGetStatsOneBlockFallback: Remove return value
      qemuDomainGetStatsOneBlock: Remove return value
      qemuDomainStorageAlias: Remove NULL checks from callers
      qemuDomainGetStatsBlockExportHeader: Remove return value
      virBitmapFormat: Clarify returned values
      virDomainResctrlMonDefParse: Refactor temporary variables
      virDomainCputuneDefFormat: Refactor bitmap formatting
      virBitmapFormat: Don't check return value
      qemuDomainGetStatsCpuCgroup: Remove return value
      qemuDomainGetStatsCpuProc: Remove return value
      qemuDomainGetStatsCpuHaltPollTime: Remove return value
      qemuDomainGetStatsCpuCache: Don't error out
      virPerfReadEvent: Refactor to return -errno on failure
      qemuDomainGetStatsPerfOneEvent: Ignore erros from 'virPerfReadEvent'
      qemuDomainGetStatsIOThread: Don't error out if fetching iothread info fails
      qemuDomainGetStatsMemoryBandwidth: Don't error out
      qemuDomainGetStatsDirtyRate: Don't error out
      qemuDomainGetStats: Convert worker functions to void
      docs: formatdomain: Document few NVRAM config limitations
      docs: formatdomain: Mention that vhostuser interface with mode='server' waits for connection
      conf: Rename 'virDomainDiskIothreadDef' to 'virDomainIothreadMappingDef'
      conf: domain: Extract code for parsing and formatting iothread mapping definition
      hypervisor: domain: Extract code for checking iothread usage
      qemu: command: Rename 'qemuBuildDiskDeviceIothreadMappingProps' to 'qemuBuildIothreadMappingProps'
      qemu: validate: Extract iothread mapping validation code
      qemuValidateCheckSCSIControllerIOThreads: Return '0' and '-1' instead of bools
      conf: schemas: Rename 'diskDriverIothreads' to 'iothreadMapping'
      conf: Validate that iothreads are used only with 'virtio-scsi' controllers
      qemucapabilitiestest: Update 'caps_10.0.0_x86_64' to 'v9.2.0-1967-gb69801dd6b'

Philipp Schuster (1):
      virsh: pool-list: remove unnecessary spaces to align behavior

Purna Pavan Chandra Aekkaladevi (5):
      ch: pass --event-monitor option to cloud-hypervisor
      ch: start a new thread for handling ch events
      ch: events: Read and parse cloud-hypervisor events
      ch: events: facilitate lifecycle events handling
      NEWS: Mention event handling support in ch driver

Remus-Gabriel Chelu (2):
      Translated using Weblate (Romanian)
      Translated using Weblate (Romanian)

Salvatore Cocuzza (1):
      Translated using Weblate (Italian)

Shalini Chellathurai Saroja (1):
      tests: add capabilities for QEMU 10.0.0 on s390x

Temuri Doghonadze (1):
      Translated using Weblate (Georgian)

Weblate (2):
      Translated using Weblate (Georgian)
      Update translation files

Yuri Chornoivan (1):
      Translated using Weblate (Ukrainian)

jianqing yan (1):
      Translated using Weblate (Chinese (Simplified) (zh_CN))

kaihuan (1):
      qemuSnapshotDeleteValidate: Fix crash when disk is not found in VM definition

김인수 (3):
      Translated using Weblate (Korean)
      Translated using Weblate (Korean)
      Translated using Weblate (Korean)